// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, key_hash, key_prefix, rate_per_sec, burst)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, key_prefix, rate_per_sec, burst, active, created_at
`

type CreateAPIKeyParams struct {
	Name       string
	KeyHash    []byte
	KeyPrefix  string
	RatePerSec float64
	Burst      int32
}

type CreateAPIKeyRow struct {
	ID         int64
	Name       string
	KeyPrefix  string
	RatePerSec float64
	Burst      int32
	Active     bool
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.RatePerSec,
		arg.Burst,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.RatePerSec,
		&i.Burst,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, rate_per_sec, burst, active, created_at
FROM api_keys
ORDER BY id
`

type ListAPIKeysRow struct {
	ID         int64
	Name       string
	KeyPrefix  string
	RatePerSec float64
	Burst      int32
	Active     bool
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.RatePerSec,
			&i.Burst,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAPIKeys = `-- name: ListActiveAPIKeys :many
SELECT id, name, key_hash, key_prefix, rate_per_sec, burst
FROM api_keys
WHERE active
`

type ListActiveAPIKeysRow struct {
	ID         int64
	Name       string
	KeyHash    []byte
	KeyPrefix  string
	RatePerSec float64
	Burst      int32
}

func (q *Queries) ListActiveAPIKeys(ctx context.Context) ([]ListActiveAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listActiveAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAPIKeysRow{}
	for rows.Next() {
		var i ListActiveAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.RatePerSec,
			&i.Burst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET active = false WHERE name = $1 AND active
`

func (q *Queries) RevokeAPIKey(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
