// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertLedgerEntries implements pgx.CopyFromSource.
type iteratorForInsertLedgerEntries struct {
	rows                 []InsertLedgerEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLedgerEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLedgerEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RequestID,
		r.rows[0].CreatedAt,
		r.rows[0].TenantID,
		r.rows[0].Source,
		r.rows[0].EndUser,
		r.rows[0].RequestedModel,
		r.rows[0].Provider,
		r.rows[0].Model,
		r.rows[0].Stream,
		r.rows[0].Cache,
		r.rows[0].Similarity,
		r.rows[0].Status,
		r.rows[0].ErrorCode,
		r.rows[0].Attempts,
		r.rows[0].PromptTokens,
		r.rows[0].CompletionTokens,
		r.rows[0].UsageEstimated,
		r.rows[0].CostUsd,
		r.rows[0].EmbeddingCostUsd,
		r.rows[0].SavedUsd,
		r.rows[0].LatencyMs,
		r.rows[0].TtfbMs,
		r.rows[0].OverheadMs,
	}, nil
}

func (r iteratorForInsertLedgerEntries) Err() error {
	return nil
}

func (q *Queries) InsertLedgerEntries(ctx context.Context, arg []InsertLedgerEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ledger"}, []string{"request_id", "created_at", "tenant_id", "source", "end_user", "requested_model", "provider", "model", "stream", "cache", "similarity", "status", "error_code", "attempts", "prompt_tokens", "completion_tokens", "usage_estimated", "cost_usd", "embedding_cost_usd", "saved_usd", "latency_ms", "ttfb_ms", "overhead_ms"}, &iteratorForInsertLedgerEntries{rows: arg})
}
