// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLedgerBefore = `-- name: DeleteLedgerBefore :execrows
DELETE FROM ledger
WHERE request_id IN (
    SELECT old.request_id FROM ledger AS old
    WHERE old.created_at < $1
    LIMIT $2
)
`

type DeleteLedgerBeforeParams struct {
	Cutoff    pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) DeleteLedgerBefore(ctx context.Context, arg DeleteLedgerBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLedgerBefore, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMaintenanceRun = `-- name: GetMaintenanceRun :one
SELECT last_run FROM maintenance_runs WHERE job = $1
`

func (q *Queries) GetMaintenanceRun(ctx context.Context, job string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getMaintenanceRun, job)
	var last_run pgtype.Timestamptz
	err := row.Scan(&last_run)
	return last_run, err
}

type InsertLedgerEntriesParams struct {
	RequestID        string
	CreatedAt        pgtype.Timestamptz
	TenantID         int64
	Source           string
	EndUser          pgtype.Text
	RequestedModel   string
	Provider         pgtype.Text
	Model            pgtype.Text
	Stream           bool
	Cache            string
	Similarity       pgtype.Float4
	Status           int16
	ErrorCode        pgtype.Text
	Attempts         []byte
	PromptTokens     int32
	CompletionTokens int32
	UsageEstimated   bool
	CostUsd          float64
	EmbeddingCostUsd float64
	SavedUsd         float64
	LatencyMs        int32
	TtfbMs           pgtype.Int4
	OverheadMs       pgtype.Int4
}

const upsertMaintenanceRun = `-- name: UpsertMaintenanceRun :exec
INSERT INTO maintenance_runs (job, last_run) VALUES ($1, $2)
ON CONFLICT (job) DO UPDATE SET last_run = EXCLUDED.last_run
`

type UpsertMaintenanceRunParams struct {
	Job     string
	LastRun pgtype.Timestamptz
}

func (q *Queries) UpsertMaintenanceRun(ctx context.Context, arg UpsertMaintenanceRunParams) error {
	_, err := q.db.Exec(ctx, upsertMaintenanceRun, arg.Job, arg.LastRun)
	return err
}
