// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int64
	Name       string
	KeyHash    []byte
	KeyPrefix  string
	RatePerSec float64
	Burst      int32
	Active     bool
	CreatedAt  pgtype.Timestamptz
}

type Ledger struct {
	RequestID        string
	CreatedAt        pgtype.Timestamptz
	TenantID         int64
	Source           string
	EndUser          pgtype.Text
	RequestedModel   string
	Provider         pgtype.Text
	Model            pgtype.Text
	Stream           bool
	Cache            string
	Similarity       pgtype.Float4
	Status           int16
	ErrorCode        pgtype.Text
	Attempts         []byte
	PromptTokens     int32
	CompletionTokens int32
	UsageEstimated   bool
	CostUsd          float64
	EmbeddingCostUsd float64
	SavedUsd         float64
	LatencyMs        int32
	TtfbMs           pgtype.Int4
	OverheadMs       pgtype.Int4
}

type MaintenanceRun struct {
	Job     string
	LastRun pgtype.Timestamptz
}
